In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [2]:
p_interest = pd.read_csv("C:/Users/Aaditya Gupta/OneDrive/Desktop/AML_A3_M1/papers_of_interest.csv")

In [4]:
daily = pd.read_csv("C:/Users/Aaditya Gupta/OneDrive/Desktop/AML_A3_M1/daily_arxiv_papers.csv")

In [ ]:
!pip install -U sentence-transformers


In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-mpnet-base-v2")

In [9]:
abstract_emd=[]
for i in range(len(daily)):
    emd = model.encode(daily['abstract'][i])
    abstract_emd.append(emd)
abstract_emd = np.array(abstract_emd)

In [13]:
daily['abs_emb'] = abstract_emd.tolist()

In [14]:
title_emd=[]
for i in range(len(daily)):
    emd = model.encode(daily['title'][i])
    title_emd.append(emd)
daily['title_emb'] = title_emd
title_emd = np.array(title_emd)

In [15]:
print(abstract_emd.shape, len(p_interest), len(daily))

(938, 768) 313 938


In [16]:
daily.head()

id  \
0  oai:arXiv.org:2403.19669v1   
1  oai:arXiv.org:2403.19717v1   
2  oai:arXiv.org:2403.19721v1   
3  oai:arXiv.org:2403.19792v1   
4  oai:arXiv.org:2403.19800v1   

                                               title  \
0  Analyzing the Roles of Language and Vision in ...   
1  A Picture is Worth 500 Labels: A Case Study of...   
2  Computationally and Memory-Efficient Robust Pr...   
3         MAPL: Model Agnostic Peer-to-peer Learning   
4  Gegenbauer Graph Neural Networks for Time-vary...   

                                            abstract         date  \
0  arXiv:2403.19669v1 Announce Type: new  Abstrac...  01-Apr-2024   
1  arXiv:2403.19717v1 Announce Type: new  Abstrac...  01-Apr-2024   
2  arXiv:2403.19721v1 Announce Type: new  Abstrac...  01-Apr-2024   
3  arXiv:2403.19792v1 Announce Type: new  Abstrac...  01-Apr-2024   
4  arXiv:2403.19800v1 Announce Type: new  Abstrac...  01-Apr-2024   

                                             abs_emb  \
0  [0.017098456621170044, 0.03898002952337265, -0...   
1  [0.03491734713315964, 0.0838918387889862, -0.0...   
2  [-0.04559684544801712, 0.08678299933671951, -0...   
3  [0.022128501906991005, 0.07788766920566559, 0....   
4  [-0.03688305988907814, 0.07381314039230347, 0....   

                                           title_emb  
0  [0.02266968, 0.08227675, -0.045680787, 0.04368...  
1  [0.027676515, 0.07284404, -0.034094423, -0.042...  
2  [0.0033859517, 0.1171573, -0.06582342, -0.0120...  
3  [-0.04529728, 0.09195001, 0.013698801, 0.02492...  
4  [-0.041430797, 0.074615225, 0.0045213224, -0.0...

In [17]:
import joblib

joblib.dump(daily,"C:/Users/Aaditya Gupta/OneDrive/Desktop/AML_A3_M1/daily_embd.joblib")

['C:/Users/Aaditya Gupta/OneDrive/Desktop/AML_A3_M1/daily_embd.joblib']

In [19]:
summary_my_list = joblib.load("C:/Users/Aaditya Gupta/OneDrive/Desktop/AML_A3_M1/summary.joblib")
title_my_list = joblib.load("C:/Users/Aaditya Gupta/OneDrive/Desktop/AML_A3_M1/title.joblib")

In [21]:
p_interest_2 = joblib.load("C:/Users/Aaditya Gupta/OneDrive/Desktop/AML_A3_M1/papers_of_interest_with_summary_title.joblib")

In [23]:
p_interest_2.head()
summary_emd=[]
for i in range(len(p_interest_2)):
    emd = model.encode(p_interest_2['summary'][i])
    summary_emd.append(emd)
summary_emd = np.array(summary_emd)

title_emd=[]
for i in range(len(p_interest_2)):
    emd = model.encode(p_interest_2['title'][i])
    title_emd.append(emd)
p_interest_2['title_emb'] = title_emd
title_emd = np.array(title_emd)



In [26]:
p_interest_2['summary_emb'] = summary_emd.tolist()

In [27]:
p_interest_2.head()

no                                   url  \
0   1  https://arxiv.org/pdf/2209.11142.pdf   
1   2  https://arxiv.org/pdf/2212.02475.pdf   
2   3  https://arxiv.org/pdf/2211.16564.pdf   
3   4      https://arxiv.org/abs/1803.05316   
4   5      https://arxiv.org/abs/2206.08896   

                                             summary  \
0  The cornerstone of neural algorithmic reasonin...   
1  Dynamic evaluation of language models (LMs) ad...   
2  The GLOM architecture proposed by Hinton [2021...   
3  This book is an invitation to discover advance...   
4  This paper pursues the insight that large lang...   

                                               title  \
0            A Generalist Neural Algorithmic Learner   
1          Meta-Learning Fast Weight Language Models   
2  Testing GLOM's ability to infer wholes from am...   
3  Seven Sketches in Compositionality: An Invitat...   
4                     Evolution through Large Models   

                                           title_emb  \
0  [0.0050590066, 0.075324915, -0.021246592, -0.0...   
1  [0.035396647, 0.039115362, 0.021043783, 0.0258...   
2  [0.012229637, 0.07378764, -0.011308909, 0.0535...   
3  [0.034200516, 0.040522955, -0.051570572, -0.00...   
4  [-0.030068131, 0.08170434, -0.031072088, -0.00...   

                                         summary_emb  
0  [0.014286473393440247, 0.04717475548386574, 0....  
1  [0.0034925471991300583, 0.062363401055336, -0....  
2  [0.022099114954471588, 0.0502488948404789, 0.0...  
3  [-0.01335581298917532, 0.06820952147245407, -0...  
4  [-0.003080987837165594, 0.06612099707126617, -...

In [121]:
joblib.dump(p_interest_2,"C:/Users/Aaditya Gupta/OneDrive/Desktop/AML_A3_M1/p_interest_2_embd.joblib")

['C:/Users/Aaditya Gupta/OneDrive/Desktop/AML_A3_M1/p_interest_2_embd.joblib']

In [30]:
daily.head()

id  \
0  oai:arXiv.org:2403.19669v1   
1  oai:arXiv.org:2403.19717v1   
2  oai:arXiv.org:2403.19721v1   
3  oai:arXiv.org:2403.19792v1   
4  oai:arXiv.org:2403.19800v1   

                                               title  \
0  Analyzing the Roles of Language and Vision in ...   
1  A Picture is Worth 500 Labels: A Case Study of...   
2  Computationally and Memory-Efficient Robust Pr...   
3         MAPL: Model Agnostic Peer-to-peer Learning   
4  Gegenbauer Graph Neural Networks for Time-vary...   

                                            abstract         date  \
0  arXiv:2403.19669v1 Announce Type: new  Abstrac...  01-Apr-2024   
1  arXiv:2403.19717v1 Announce Type: new  Abstrac...  01-Apr-2024   
2  arXiv:2403.19721v1 Announce Type: new  Abstrac...  01-Apr-2024   
3  arXiv:2403.19792v1 Announce Type: new  Abstrac...  01-Apr-2024   
4  arXiv:2403.19800v1 Announce Type: new  Abstrac...  01-Apr-2024   

                                             abs_emb  \
0  [0.017098456621170044, 0.03898002952337265, -0...   
1  [0.03491734713315964, 0.0838918387889862, -0.0...   
2  [-0.04559684544801712, 0.08678299933671951, -0...   
3  [0.022128501906991005, 0.07788766920566559, 0....   
4  [-0.03688305988907814, 0.07381314039230347, 0....   

                                           title_emb  
0  [0.02266968, 0.08227675, -0.045680787, 0.04368...  
1  [0.027676515, 0.07284404, -0.034094423, -0.042...  
2  [0.0033859517, 0.1171573, -0.06582342, -0.0120...  
3  [-0.04529728, 0.09195001, 0.013698801, 0.02492...  
4  [-0.041430797, 0.074615225, 0.0045213224, -0.0...

In [31]:
print(np.array(p_interest_2['title_emb'][0]).shape,
np.array(p_interest_2['summary_emb'][0]).shape,
np.array(daily['title_emb'][0]).shape,
np.array(daily['abs_emb'][0]).shape,)

(768,) (768,) (768,) (768,)


In [33]:
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances
# # Example vectors
# vector1 = np.array([1, 2, 3, 4])
# vector2 = np.array([2, 3, 4, 5])

# # Reshape the vectors to ensure they are 2D arrays
# vector1 = vector1.reshape(1, -1)
# vector2 = vector2.reshape(1, -1)

# # Compute cosine similarity
# cosine_sim = cosine_similarity(vector1, vector2)
# print("Cosine Similarity:", cosine_sim[0][0])

# # Compute Euclidean distance
# euclidean_dist = euclidean_distances(vector1, vector2)
# print("Euclidean Distance:", euclidean_dist[0][0])

cos_score_title=[]
euc_dis_title=[]
cos_score_summary=[]
euc_dis_summary=[]
for i in range(len(p_interest_2)):
    cos_title=[]
    cos_summary=[]
    euc_title=[]
    euc_summary=[]
    t_p = np.array(p_interest_2['title_emb'][i]).reshape(1,-1)
    s_p = np.array(p_interest_2['summary_emb'][i]).reshape(1,-1)
    for j in range(len(daily)):
        t_d = np.array(daily['title_emb'][j]).reshape(1,-1)
        s_d = np.array(daily['abs_emb'][j]).reshape(1,-1)
        cos_title.append(cosine_similarity(t_p, t_d))
        cos_summary.append(cosine_similarity(s_p, s_d))
        euc_title.append(euclidean_distances(t_p, t_d))
        euc_summary.append(euclidean_distances(s_p, s_d))

    cos_score_title.append(cos_title)
    euc_dis_title.append(euc_title)
    cos_score_summary.append(cos_summary)
    euc_dis_summary.append(euc_summary)

    


        


In [47]:
cos_score_title_ = np.array(cos_score_title).reshape(313,938)
euc_dis_title_ = np.array(euc_dis_title).reshape(313,938)
cos_score_summary_ = np.array(cos_score_summary).reshape(313,938)
euc_dis_summary_ = np.array(euc_dis_summary).reshape(313,938)
# print(cos_score_title_[:10])
# cos_score_title_ = cos_score_title_.reshape(313,938)
# print(cos_score_title_[:10])

In [48]:
print(cos_score_title_.shape,
euc_dis_title_.shape,
cos_score_summary_.shape,
euc_dis_summary_.shape)

(313, 938) (313, 938) (313, 938) (313, 938)


In [54]:
def find_largest_values_indices(arr, n=10):
    indices = np.argpartition(arr, -n)[-n:]  # Get indices of n largest values
    values = arr[indices]  # Get the corresponding values
    sorted_indices = indices[np.argsort(values)][::-1]  # Sort indices by values in descending order
    sorted_values = values[np.argsort(values)][::-1]  # Sort values in descending order
    return sorted_values, sorted_indices

In [105]:
def find_smallest_values_indices(arr, n=10):
    indices = np.argpartition(arr, n)[:n]  # Get indices of n smallest values
    values = arr[indices]  # Get the corresponding values
    sorted_indices = np.sort(indices)  # Sort indices in ascending order
    sorted_values = values[np.argsort(values)]  # Sort values in ascending order
    return sorted_values, sorted_indices

In [106]:
arr=np.array([1,8,9,8,2,1,3,-10,25,78,100,123,894,-99,456])
find_smallest_values_indices(arr)

(array([-99, -10,   1,   1,   2,   3,   8,   8,   9,  25]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 13], dtype=int64))

In [55]:
print(find_largest_values_indices(cos_score_title_[0]))

(array([0.5334933 , 0.5218463 , 0.5172602 , 0.5172602 , 0.5172602 ,
       0.5123295 , 0.51229835, 0.51078105, 0.49922538, 0.49808612],
      dtype=float32), array([124, 196, 630, 554, 478,  49, 795, 432, 896, 929], dtype=int64))


In [107]:
recom_by_title_index_cos=[]
recom_by_title_score_cos=[]
for i in range(len(cos_score_title_)):
    a,b=find_largest_values_indices(cos_score_title_[i])
    recom_by_title_score_cos.append(a)
    recom_by_title_index_cos.append(b)

recom_by_summary_index_cos=[]
recom_by_summary_score_cos=[]
for i in range(len(cos_score_summary_)):
    a,b=find_largest_values_indices(cos_score_summary_[i])
    recom_by_summary_score_cos.append(a)
    recom_by_summary_index_cos.append(b)


In [108]:
recom_by_title_index_euc=[]
recom_by_title_score_euc=[]
for i in range(len(euc_dis_title_)):
    a,b=find_smallest_values_indices(euc_dis_title_[i])
    recom_by_title_score_euc.append(a)
    recom_by_title_index_euc.append(b)

recom_by_summary_index_euc=[]
recom_by_summary_score_euc=[]
for i in range(len(euc_dis_summary_)):
    a,b=find_smallest_values_indices(euc_dis_summary_[i])
    recom_by_summary_score_euc.append(a)
    recom_by_summary_index_euc.append(b)

In [114]:
recom={}
for i in range(len(p_interest_2)):
    row_i=set()
    for j in recom_by_summary_index_cos[i]:
        row_i.add(daily['title'][j])
    recom[p_interest_2['title'][i]] = row_i

In [115]:
print("Papers similar to papers_of_interest recommended via cosine similarity are :")
recom

Papers similar to papers_of_interest recommended via cosine similarity are :


{'A Generalist Neural Algorithmic Learner': {'Beyond the Known: Novel Class Discovery for Open-world Graph Learning',
  'Delayed Bottlenecking: Alleviating Forgetting in Pre-trained Graph\n  Neural Networks',
  'FR-NAS: Forward-and-Reverse Graph Predictor for Efficient Neural\n  Architecture Search',
  'GNNavigator: Towards Adaptive Training of Graph Neural Networks via\n  Automatic Guideline Exploration',
  'Graph Continual Learning with Debiased Lossless Memory Replay',
  'Graph Machine Learning in the Era of Large Language Models (LLMs)',
  'Improving the interpretability of GNN predictions through\n  conformal-based graph sparsification',
  'On the Scalability of GNNs for Molecular Graphs'},
 'Meta-Learning Fast Weight Language Models': {'CroissantLLM: A Truly Bilingual French-English Language Model',
  'DiJiang: Efficient Large Language Models through Compact Kernelization',
  'HLAT: High-quality Large Language Model Pre-trained on AWS Trainium',
  'Hierarchical Context Merging: B

In [116]:
recom_euc={}
for i in range(len(p_interest_2)):
    row_i=set()
    for j in recom_by_summary_index_euc[i]:
        # print(daily['title'][j])
        row_i.add(daily['title'][j])
    recom_euc[p_interest_2['title'][i]] = row_i

In [117]:
print("Papers similar to papers_of_interest recommended via euclidean distance are :")
recom_euc

Papers similar to papers_of_interest recommended via euclidean distance are :


{'A Generalist Neural Algorithmic Learner': {'Beyond the Known: Novel Class Discovery for Open-world Graph Learning',
  'Delayed Bottlenecking: Alleviating Forgetting in Pre-trained Graph\n  Neural Networks',
  'FR-NAS: Forward-and-Reverse Graph Predictor for Efficient Neural\n  Architecture Search',
  'GNNavigator: Towards Adaptive Training of Graph Neural Networks via\n  Automatic Guideline Exploration',
  'Graph Continual Learning with Debiased Lossless Memory Replay',
  'Graph Machine Learning in the Era of Large Language Models (LLMs)',
  'Improving the interpretability of GNN predictions through\n  conformal-based graph sparsification',
  'On the Scalability of GNNs for Molecular Graphs'},
 'Meta-Learning Fast Weight Language Models': {'CroissantLLM: A Truly Bilingual French-English Language Model',
  'DiJiang: Efficient Large Language Models through Compact Kernelization',
  'HLAT: High-quality Large Language Model Pre-trained on AWS Trainium',
  'Hierarchical Context Merging: B

##Recommendations as a combined result of the above rules:

In [118]:
for i in list(recom_euc.keys()):
    ints = recom_euc[i].intersection(recom[i])
    print("For the paper",i, " we have the following recommendation: ",ints)

For the paper A Generalist Neural Algorithmic Learner  we have the following recommendation:  {'Improving the interpretability of GNN predictions through\n  conformal-based graph sparsification', 'Graph Continual Learning with Debiased Lossless Memory Replay', 'Beyond the Known: Novel Class Discovery for Open-world Graph Learning', 'GNNavigator: Towards Adaptive Training of Graph Neural Networks via\n  Automatic Guideline Exploration', 'Graph Machine Learning in the Era of Large Language Models (LLMs)', 'Delayed Bottlenecking: Alleviating Forgetting in Pre-trained Graph\n  Neural Networks', 'FR-NAS: Forward-and-Reverse Graph Predictor for Efficient Neural\n  Architecture Search', 'On the Scalability of GNNs for Molecular Graphs'}
For the paper Meta-Learning Fast Weight Language Models  we have the following recommendation:  {'HLAT: High-quality Large Language Model Pre-trained on AWS Trainium', 'Hierarchical Context Merging: Better Long Context Understanding for\n  Pre-trained LLMs', '

In [120]:
recom_by_summary_score_euc[0], recom_by_summary_score_cos[0]

(array([0.83251965, 0.83714686, 0.83714686, 0.83714686, 0.84503516,
        0.87948477, 0.89165143, 0.89840561, 0.89925162, 0.89932382]),
 array([0.65345549, 0.64959256, 0.64959256, 0.64959256, 0.6429578 ,
        0.61325325, 0.60247883, 0.59643367, 0.59567325, 0.5956083 ]))